#Standalone to scrap down fprobe

---
- hosts: all
  become: yes
  tasks:


  - name: Remove fprobe package
    ansible.builtin.package:
      name: "fprobe"
      state: "absent"

  - name: Remove files
    ansible.builtin.file:
      path: "{{item}}"
      state: absent
    with_items:
      - /etc/init.d/fprobe
      - /etc/default/fprobe
      - /etc/rc4.d/S01fprobe
      - /etc/rc5.d/S01fprobe
      - /etc/rc3.d/S01fprobe
      - /etc/rc1.d/K01fprobe
      - /etc/rc6.d/K01fprobe
      - /etc/rc2.d/S01fprobe
      - /etc/rc0.d/K01fprobe
      - /sys/fs/cgroup/fprobe.service
      - /run/systemd/units/invocation:fprobe.service


  - name: Reload systemd daemon
    ansible.builtin.service:
      daemon_reload: yes
